[
    {
        "number": 14,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9q62-r72g-pvv7",
            "cve_id": "CVE-2019-16224",
            "summary": "py-lmdb Invalid write operation",
            "description": "An issue was discovered in py-lmdb 0.97. For certain values of `md_flags`, `mdb_node_add` does not properly set up a memcpy destination, leading to an invalid write operation. NOTE: this outcome occurs when accessing a `data.mdb` file supplied by an attacker.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-9q62-r72g-pvv7",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-16224",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16224"
                },
                {
                    "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20initialization%20vuln"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9q62-r72g-pvv7"
                }
            ],
            "published_at": "2022-05-24T16:55:55Z",
            "updated_at": "2024-04-22T22:36:14Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "lmdb"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 0.97",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 0.97",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/14",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/14",
        "created_at": "2024-05-24T01:33:59Z",
        "updated_at": "2024-05-24T01:33:59Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 13,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-c74c-p4p7-r8q5",
            "cve_id": "CVE-2019-16225",
            "summary": "py-lmdb Invalid write operation",
            "description": "An issue was discovered in py-lmdb 0.97. For certain values of `mp_flags`, `mdb_page_touch `does not properly set up `mc->mc_pg[mc->top]`, leading to an invalid write operation. NOTE: this outcome occurs when accessing a `data.mdb` file supplied by an attacker.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-c74c-p4p7-r8q5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-16225",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16225"
                },
                {
                    "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20write%20to%20illegal%20address"
                },
                {
                    "url": "https://github.com/advisories/GHSA-c74c-p4p7-r8q5"
                }
            ],
            "published_at": "2022-05-24T16:55:55Z",
            "updated_at": "2024-04-22T22:36:13Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "lmdb"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 0.97",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 0.97",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/13",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/13",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 12,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-pf3p-v9xp-mrvf",
            "cve_id": "CVE-2019-16227",
            "summary": "py-lmdb Invalid write operation",
            "description": "An issue was discovered in py-lmdb 0.97. For certain values of `mn_flags`, `mdb_cursor_set` triggers a memcpy with an invalid write operation within `mdb_xcursor_init1`. NOTE: this outcome occurs when accessing a `data.mdb` file supplied by an attacker.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-pf3p-v9xp-mrvf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-16227",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16227"
                },
                {
                    "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memcpy%20illegal%20dst"
                },
                {
                    "url": "https://github.com/advisories/GHSA-pf3p-v9xp-mrvf"
                }
            ],
            "published_at": "2022-05-24T22:00:30Z",
            "updated_at": "2024-04-22T22:36:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "lmdb"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 0.97",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 0.97",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/12",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/12",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 11,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-ggwq-vrgp-6gv4",
            "cve_id": "CVE-2019-16228",
            "summary": "py-lmdb Divide by Zero interruptions",
            "description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-ggwq-vrgp-6gv4",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-16228",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16228"
                },
                {
                    "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/FPE"
                },
                {
                    "url": "https://github.com/advisories/GHSA-ggwq-vrgp-6gv4"
                }
            ],
            "published_at": "2022-05-24T16:55:56Z",
            "updated_at": "2024-04-22T22:36:08Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "lmdb"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 0.97",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-369",
                    "name": "Divide By Zero"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 0.97",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/11",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/11",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 10,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "gevent"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-x7m3-jprg-wc5g",
            "cve_id": "CVE-2023-41419",
            "summary": "Gevent allows remote attacker to escalate privileges",
            "description": "An issue in Gevent before version 23.9.0 allows a remote attacker to escalate privileges via a crafted script to the WSGIServer component.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-x7m3-jprg-wc5g",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-41419",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-41419"
                },
                {
                    "url": "https://github.com/gevent/gevent/issues/1989"
                },
                {
                    "url": "https://github.com/gevent/gevent/commit/2f53c851eaf926767fbac62385615efd4886221c"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/gevent/PYSEC-2023-177.yaml"
                },
                {
                    "url": "http://www.gevent.org/changelog.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-x7m3-jprg-wc5g"
                }
            ],
            "published_at": "2023-09-25T12:30:44Z",
            "updated_at": "2023-11-04T05:01:16Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "gevent"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 23.9.0",
                    "first_patched_version": {
                        "identifier": "23.9.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": []
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "gevent"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 23.9.0",
            "first_patched_version": {
                "identifier": "23.9.0"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/10",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/10",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 9,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-9fq2-x9r6-wfmf",
            "cve_id": "CVE-2019-6446",
            "summary": "Numpy Deserialization of Untrusted Data",
            "description": "** DISPUTED **   An issue was discovered in NumPy 1.16.0 and earlier. It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call. NOTE: third parties dispute this issue because it is  a behavior that might have legitimate applications in (for example)  loading serialized Python object arrays from trusted and authenticated  sources.",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-9fq2-x9r6-wfmf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-6446",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-6446"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/12759"
                },
                {
                    "url": "https://bugzilla.suse.com/show_bug.cgi?id=1122208"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00091.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00092.html"
                },
                {
                    "url": "http://lists.opensuse.org/opensuse-security-announce/2019-10/msg00015.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/pull/12889"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:3335"
                },
                {
                    "url": "https://access.redhat.com/errata/RHSA-2019:3704"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7ZZAYIQNUUYXGMKHSPEEXS4TRYFOUYE4"
                },
                {
                    "url": "https://web.archive.org/web/20210124234613/https://www.securityfocus.com/bid/106670"
                },
                {
                    "url": "http://www.securityfocus.com/bid/106670"
                },
                {
                    "url": "https://github.com/advisories/GHSA-9fq2-x9r6-wfmf"
                }
            ],
            "published_at": "2022-05-24T22:00:57Z",
            "updated_at": "2024-04-22T21:20:59Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "<= 1.16.0",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-502",
                    "name": "Deserialization of Untrusted Data"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "critical",
            "vulnerable_version_range": "<= 1.16.0",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/9",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/9",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 8,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-r8g9-w4f3-9crm",
            "cve_id": "CVE-2019-16226",
            "summary": "LMDB invalid write ",
            "description": "An issue was discovered in py-lmdb 0.97. `mdb_node_del` does not validate a `memmove` in the case of an unexpected `node->mn_hi`, leading to an invalid write operation.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-r8g9-w4f3-9crm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2019-16226",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-16226"
                },
                {
                    "url": "https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln"
                },
                {
                    "url": "https://github.com/jnwatson/py-lmdb/issues/210"
                },
                {
                    "url": "https://github.com/LMDB/lmdb/blob/mdb.master/libraries/liblmdb/mdb.c#L8443-L8498"
                },
                {
                    "url": "https://github.com/advisories/GHSA-r8g9-w4f3-9crm"
                }
            ],
            "published_at": "2022-05-24T16:55:55Z",
            "updated_at": "2023-09-04T16:48:31Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "lmdb"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 0.97",
                    "first_patched_version": null
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "lmdb"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 0.97",
            "first_patched_version": null
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/8",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/8",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 7,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-r9hx-vwmv-q579",
            "cve_id": "CVE-2022-40897",
            "summary": "pypa/setuptools vulnerable to Regular Expression Denial of Service (ReDoS)",
            "description": "Python Packaging Authority (PyPA)'s setuptools is a library designed to facilitate packaging Python projects. Setuptools version 65.5.0 and earlier could allow remote attackers to cause a denial of service by fetching malicious HTML from a PyPI package or custom PackageIndex page due to a vulnerable Regular Expression in `package_index`. This has been patched in version 65.5.1.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-r9hx-vwmv-q579",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-40897",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-40897"
                },
                {
                    "url": "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200"
                },
                {
                    "url": "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/"
                },
                {
                    "url": "https://github.com/pypa/setuptools/issues/3659"
                },
                {
                    "url": "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be"
                },
                {
                    "url": "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1"
                },
                {
                    "url": "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/"
                },
                {
                    "url": "https://setuptools.pypa.io/en/latest/"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20230214-0001/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-r9hx-vwmv-q579"
                }
            ],
            "published_at": "2022-12-23T00:30:23Z",
            "updated_at": "2023-05-01T13:43:54Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "setuptools"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 65.5.1",
                    "first_patched_version": {
                        "identifier": "65.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-1333",
                    "name": "Inefficient Regular Expression Complexity"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "setuptools"
            },
            "severity": "high",
            "vulnerable_version_range": "< 65.5.1",
            "first_patched_version": {
                "identifier": "65.5.1"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/7",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/7",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 6,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "protobuf"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-8gq9-2x98-w8hf",
            "cve_id": "CVE-2022-1941",
            "summary": "protobuf-cpp and protobuf-python have potential Denial of Service issue",
            "description": "### Summary\n\nA message parsing and memory management vulnerability in ProtocolBuffer’s C++ and Python implementations can trigger an out of memory (OOM) failure when processing a specially crafted message, which could lead to a denial of service (DoS) on services using the libraries.\n\nReporter: [ClusterFuzz](https://google.github.io/clusterfuzz/)\n\nAffected versions: All versions of C++ Protobufs (including Python) prior to the versions listed below.\n\n### Severity & Impact\nAs scored by google  \n**Medium 5.7** - [CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:A/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H)  \nAsscored byt NIST  \n**High 7.5** - [CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H](https://www.first.org/cvss/calculator/3.1#CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H)\n\nA small (~500 KB) malicious payload can be constructed which causes the running service to allocate more than 3GB of RAM.\n\n### Proof of Concept\n\nFor reproduction details, please refer to the unit test that identifies the specific inputs that exercise this parsing weakness.\n\n### Mitigation / Patching\n\nPlease update to the latest available versions of the following packages:\n- protobuf-cpp (3.18.3, 3.19.5, 3.20.2, 3.21.6)\n- protobuf-python (3.18.3, 3.19.5, 3.20.2, 4.21.6)",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-8gq9-2x98-w8hf",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-1941",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-8gq9-2x98-w8hf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-1941"
                },
                {
                    "url": "https://cloud.google.com/support/bulletins#GCP-2022-019"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2022/09/27/1"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CBAUKJQL6O4TIWYBENORSY5P43TVB4M3/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/04/msg00019.html"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MPCGUT3T5L6C3IDWUPSUO22QDCGQKTOP/"
                },
                {
                    "url": "https://github.com/advisories/GHSA-8gq9-2x98-w8hf"
                }
            ],
            "published_at": "2022-09-23T20:31:15Z",
            "updated_at": "2023-04-27T15:52:06Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.18.3",
                    "first_patched_version": {
                        "identifier": "3.18.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 3.19.0, < 3.19.5",
                    "first_patched_version": {
                        "identifier": "3.19.5"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 3.20.0, < 3.20.2",
                    "first_patched_version": {
                        "identifier": "3.20.2"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 4.0.0, < 4.21.6",
                    "first_patched_version": {
                        "identifier": "4.21.6"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-119",
                    "name": "Improper Restriction of Operations within the Bounds of a Memory Buffer"
                },
                {
                    "cwe_id": "CWE-1286",
                    "name": "Improper Validation of Syntactic Correctness of Input"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "protobuf"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.18.3",
            "first_patched_version": {
                "identifier": "3.18.3"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/6",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/6",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 5,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fpfv-jqm9-f5jm",
            "cve_id": "CVE-2021-34141",
            "summary": "Incorrect Comparison in NumPy",
            "description": "Incomplete string comparison in the numpy.core component in NumPy1.9.x, which allows attackers to fail the APIs via constructing specific string objects.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fpfv-jqm9-f5jm",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-34141",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-34141"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml"
                }
            ],
            "published_at": "2021-12-18T00:00:41Z",
            "updated_at": "2023-01-27T05:07:10Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 1.22",
                    "first_patched_version": {
                        "identifier": "1.22"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                "score": 5.3
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 1.22",
            "first_patched_version": {
                "identifier": "1.22"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/5",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/5",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 4,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5545-2q6w-2gh6",
            "cve_id": "CVE-2021-41495",
            "summary": "NumPy NULL Pointer Dereference",
            "description": "Null Pointer Dereference vulnerability exists in numpy.sort in NumPy &lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5545-2q6w-2gh6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41495",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41495"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/19038"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5545-2q6w-2gh6"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml"
                }
            ],
            "published_at": "2022-02-08T00:00:56Z",
            "updated_at": "2023-01-29T05:01:55Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "<= 1.18.5",
                    "first_patched_version": {
                        "identifier": "1.19"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "high",
            "vulnerable_version_range": "<= 1.18.5",
            "first_patched_version": {
                "identifier": "1.19"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/4",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/4",
        "created_at": "2024-05-24T01:33:58Z",
        "updated_at": "2024-05-24T01:33:58Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 3,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f7c7-j99h-c22f",
            "cve_id": "CVE-2021-41496",
            "summary": "Buffer Copy without Checking Size of Input in NumPy",
            "description": "Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy < 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-f7c7-j99h-c22f",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-41496",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-41496"
                },
                {
                    "url": "https://github.com/numpy/numpy/issues/19000"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpujul2022.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f7c7-j99h-c22f"
                }
            ],
            "published_at": "2022-02-08T00:00:56Z",
            "updated_at": "2023-01-27T05:02:20Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "numpy"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "<= 1.18.5",
                    "first_patched_version": {
                        "identifier": "1.19"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "numpy"
            },
            "severity": "medium",
            "vulnerable_version_range": "<= 1.18.5",
            "first_patched_version": {
                "identifier": "1.19"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/3",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/3",
        "created_at": "2024-05-24T01:33:57Z",
        "updated_at": "2024-05-24T01:33:57Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 2,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "protobuf"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jwvw-v7c5-m82h",
            "cve_id": "CVE-2015-5237",
            "summary": "protobuf susceptible to buffer overflow",
            "description": "protobuf allows remote authenticated attackers to cause a heap-based buffer overflow.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-jwvw-v7c5-m82h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2015-5237",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2015-5237"
                },
                {
                    "url": "https://github.com/google/protobuf/issues/760"
                },
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1256426"
                },
                {
                    "url": "https://lists.apache.org/thread.html/519eb0fd45642dcecd9ff74cb3e71c20a4753f7d82e2f07864b5108f@%3Cdev.drill.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/b0656d359c7d40ec9f39c8cc61bca66802ef9a2a12ee199f5b0c1442@%3Cdev.drill.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/f9bc3e55f4e28d1dcd1a69aae6d53e609a758e34d2869b4d798e13cc@%3Cissues.drill.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r00097d0b5b6164ea428554007121d5dc1f88ba2af7b9e977a10572cd@%3Cdev.hbase.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r00d9ab1fc0f1daf14cd4386564dd84f7889404438d81462c86dfa836@%3Ccommon-dev.hadoop.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r02e39d7beb32eebcdbb4b516e95f67d71c90d5d462b26f4078d21eeb@%3Cdev.flink.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r02e39d7beb32eebcdbb4b516e95f67d71c90d5d462b26f4078d21eeb@%3Cuser.flink.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r0ca83171c4898dc92b86fa6f484a7be1dc96206765f4d01dce0f1b28@%3Ccommon-issues.hadoop.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r1263fa5b51e4ec3cb8f09ff40e4747428c71198e9bee93349ec96a3c@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r14fa8d38d5757254f1a2e112270c996711d514de2e3b01c93d397ab4@%3Cissues.spark.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r17dc6f394429f6bffb5e4c66555d93c2e9923cbbdc5a93db9a56c1c7@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r1d274d647b3c2060df9be21eade4ce56d3a59998cf19ac72662dd994@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r2ea33ce5591a9cb9ed52750b6ab42ab658f529a7028c3166ba93c7d5@%3Ccommon-issues.hadoop.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r320dc858da88846ba00bb077bcca2cdf75b7dde0f6eb3a3d60dba6a1@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r42e47994734cd1980ef3e204a40555336e10cc80096927aca2f37d90@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r42ef6acfb0d86a2df0c2390702ecbe97d2104a331560f2790d17ca69@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r4886108206d4c535db9b20c813fe4723d4fe6a91b9278382af8b9d08@%3Cissues.spark.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r4ef574a5621b0e670a3ce641e9922543e34f22bf4c9ee9584aa67fcf@%3Cissues.hbase.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r5741f4dbdd129dbb9885f5fb170dc1b24a06b9313bedef5e67fded94@%3Cissues.spark.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r5e52caf41dc49df55b4ee80758356fe1ff2a88179ff24c685de7c28d@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r764fc66435ee4d185d359c28c0887d3e5866d7292a8d5598d9e7cbc4@%3Ccommon-issues.hadoop.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r7fed8dd9bee494094e7011cf3c2ab75bd8754ea314c6734688c42932@%3Ccommon-issues.hadoop.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/r85c9a764b573c786224688cc906c27e28343e18f5b33387f94cae90f@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/ra28fed69eef3a71e5fe5daea001d0456b05b102044237330ec5c7c82@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/rb40dc9d63a5331bce8e80865b7fa3af9dd31e16555affd697b6f3526@%3Cissues.spark.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/rb71dac1d9dd4e8a8ae3dbc033aeae514eda9be1263c1df3b42a530a2@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/rd64381fb8f92d640c1975dc50dcdf1b8512e02a2a7b20292d3565cae@%3Cissues.hbase.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/re6d04a214424a97ea59c62190d79316edf311a0a6346524dfef3b940@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "https://lists.apache.org/thread.html/rf7539287c90be979bac94af9aaba34118fbf968864944b4871af48dd@%3Ccommits.pulsar.apache.org%3E"
                },
                {
                    "url": "http://www.openwall.com/lists/oss-security/2015/08/27/2"
                },
                {
                    "url": "https://github.com/google/protobuf/releases/tag/v3.4.0"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jwvw-v7c5-m82h"
                },
                {
                    "url": "https://github.com/pypa/advisory-database/tree/main/vulns/protobuf/PYSEC-2017-65.yaml"
                }
            ],
            "published_at": "2022-05-13T01:06:54Z",
            "updated_at": "2023-01-29T05:02:06Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "Google.Protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.4.0",
                    "first_patched_version": {
                        "identifier": "3.4.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "maven",
                        "name": "com.google.protobuf:protobuf-parent"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.4.0",
                    "first_patched_version": {
                        "identifier": "3.4.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "go",
                        "name": "github.com/protocolbuffers/protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.4.0",
                    "first_patched_version": {
                        "identifier": "3.4.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "composer",
                        "name": "google/protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.4.0",
                    "first_patched_version": {
                        "identifier": "3.4.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.4.0",
                    "first_patched_version": {
                        "identifier": "3.4.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 8.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "protobuf"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.4.0",
            "first_patched_version": {
                "identifier": "3.4.0"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/2",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/2",
        "created_at": "2024-05-24T01:33:57Z",
        "updated_at": "2024-05-24T01:33:57Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 1,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "protobuf"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-77rm-9x9h-xj3g",
            "cve_id": "CVE-2021-22570",
            "summary": "NULL Pointer Dereference in Protocol Buffers",
            "description": "Nullptr dereference when a null char is present in a proto symbol. The symbol is parsed incorrectly, leading to an unchecked call into the proto file's name during generation of the resulting error message. Since the symbol is incorrectly parsed, the file is nullptr. We recommend upgrading to version 3.15.0 or greater.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-77rm-9x9h-xj3g",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-22570",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-22570"
                },
                {
                    "url": "https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.0"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IFX6KPNOFHYD6L4XES5PCM3QNSKZBOTQ/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/3DVUZPALAQ34TQP6KFNLM4IZS6B32XSA/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/BTRGBRC5KGCA4SK5MUNLPYJRAGXMBIYY/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NVTWVQRB5OCCTMKEQFY5MYED3DXDVSLP/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PAGL5M2KGYPN3VEQCRJJE6NA7D5YG5X/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KQJB6ZPRLKV6WCMX2PRRRQBFAOXFBK6B/"
                },
                {
                    "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MRWRAXAFR3JR7XCFWTHC2KALSZKWACCE/"
                },
                {
                    "url": "https://www.oracle.com/security-alerts/cpuapr2022.html"
                },
                {
                    "url": "https://security.netapp.com/advisory/ntap-20220429-0005/"
                },
                {
                    "url": "https://lists.debian.org/debian-lts-announce/2023/04/msg00019.html"
                },
                {
                    "url": "https://github.com/advisories/GHSA-77rm-9x9h-xj3g"
                }
            ],
            "published_at": "2022-01-27T00:01:15Z",
            "updated_at": "2023-08-16T05:02:15Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "nuget",
                        "name": "Google.Protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.15.0",
                    "first_patched_version": {
                        "identifier": "3.15.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "composer",
                        "name": "google/protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.15.0",
                    "first_patched_version": {
                        "identifier": "3.15.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "go",
                        "name": "github.com/protocolbuffers/protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.15.0",
                    "first_patched_version": {
                        "identifier": "3.15.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "protobuf"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.15.0",
                    "first_patched_version": {
                        "identifier": "3.15.0"
                    }
                },
                {
                    "package": {
                        "ecosystem": "maven",
                        "name": "com.google.protobuf:protobuf-java"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 3.15.0",
                    "first_patched_version": {
                        "identifier": "3.15.0"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "protobuf"
            },
            "severity": "high",
            "vulnerable_version_range": "< 3.15.0",
            "first_patched_version": {
                "identifier": "3.15.0"
            }
        },
        "url": "https://api.github.com/repos/username/DIGITS/dependabot/alerts/1",
        "html_url": "https://github.com/username/DIGITS/security/dependabot/1",
        "created_at": "2024-05-24T01:33:57Z",
        "updated_at": "2024-05-24T01:33:57Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]